User Stories
polinkot/airline pull request #2
Opened 2021-05-10 10:47 UTC by polinkot

2021-05-11 06:49 UTC, elukianov requested changes

2021-05-11 06:49 UTC, elukianov commented on 1_requirements.txt
> +https://miro.com/app/board/o9J_lFzv_no=/
Несколько комментариев по карте. 

1. Слабо освещена работа отдела лизинга. Прежде чем самолёт добавить - нам нужно его принять и завести. Аэропорт может быть справочником, у самолёта же есть свой жизненный цикл, поэтому этот момент нужно уточнить. 

2. Для начала лучше оперировать не списком рейсов, а  отдельным конкретным рейсом, потому что нам нужно разработать процедуру добавления рейса. Далее уже можно будет думать как их публиковать пачкой. 

3. "Нажимает Выбрать" - мы пока не знаем как будет выглядеть интерфейс, поэтому такая формулировка диктует нам какие-то детали

4. Личный кабинет (...) - выгялдит как фича, от которой мы и пытаемся уйти. Из неё непонятно, что может делать пользователь. 

5. Скидки на билеты - аналогично

6. Создаем новый заказ в БД - детали

7. Отправка e-mail * - лучше описать это с точки зрения пользователей. Менеджер рейса получает письмо с информацией о полёте, что-то в этом роде

2021-05-13 13:35 UTC, polinkot commented on 1_requirements.txt
> +https://miro.com/app/board/o9J_lFzv_no=/
Исправила. Старалась убрать технические детали. https://miro.com/app/board/o9J_lFzv_no=/

2021-05-14 13:34 UTC, elukianov commented on 1_requirements.txt
> +https://miro.com/app/board/o9J_lFzv_no=/
Гораздо лучше!

2021-05-14 13:36 UTC, elukianov approved these changes

2021-05-14 13:36 UTC, merged