Бизнес-логика
polinkot/airline pull request #28
Opened 2021-07-24 17:45 UTC by polinkot

2021-07-24 17:47 UTC, polinkot commented
Привет.
Сделала domain для авиакомпании. Присылаю на ревью. Правда, не сделала отдельную ветку для кода. Всё уже в main.
Сразу добавила usecase, persistence, web. Они пока пустые.

Модуль leasing - контекст лизинг.
Модуль flight - управление рейсами.
Модуль maintenance - ТО.

Вопросы:

Выбирала как поместить в агрегат вложенные сущности. Например - самолёт для рейса.
class Flight internal constructor(
        id: FlightId,
        val aircraftId: AircraftId
        ...
)
В виде объектов? Или айдишек?
Решила, что всё-таки лучше айдишки, ведь у нас может и не быть хибернейта, кэшей.
И если всегда собирать агрегат со всеми вложенными объектами, то получится нагрузка на память и потеря производительности.
А эти объекты могут и не понадобиться совсем. Мы сможем доставать их из хранилища целиком потом, когда потребуются.
Как всё-таки лучше делать?

Не разобралась - когда использовать DomainEntity, когда агрегат?
Если есть вложенные сущности, которые должны сохраняться только вместе с содержащим их объектом - то агрегат?
Например - айтемы у заказа.
А если вложенные могут сохраняться отдельно? Тогда DomainEntity? Или тоже агрегат?
Например - самолёт у рейса. Их ведь не нужно сохранять в одной транзакции.

2021-07-27 10:55 UTC, elukianov commented
**Commons**
- common/types - нет тестов
- в сборке закомменчены minimum = BigDecimal("0.8"), видимо поэтому и собралось
- Опционально: Airport можно было трехзначный код (IATA кажется).

**Контекст лизинга.** 
- Опционально: SeatMap можно было упростить даже немного, просто внутри самолёта сделать что-то типа List<Seat(1A)>

**Контекст обслуживания**
- Опционально:FlightDuration - тут можно просто джавовый Duration взять даже. 
- Flight - у нас на шторминге 2 события, Рейс зареган(тут я поправил немного, там ошибка была в названии события) и Рейс прибыл. А методов и событий в коде 3, что не соответствует модели. 

**Контекст полётов:**
- Aircraft.create - у нас в модели эта команда называется Получить информацию о ВС. Думаю стоит переименовать метод (Событие называется AircraftInfoReceivedDomainEvent). 
- Fio - FullName же =)
- OrderItem думаю можно сделать data классом
- Order - у нас в модели всего 2 состояния, а я вижу 3
- Order.price - можно сделать val, вроде нигде не меняется
- Опционально: LessThanHourTillDeparture - тут вообще можно сделать универсально правило, типа Х времени до вылета, не обязательно час. И проверять прямо в агрегате, без отдельного интерфейса для правила. Я по этому поводу в чятике писал недавно (где реализовывать правила)

Отдельно подчеркну почему важно именование и следование модели - это часть единого языка, который сильно облегчает нам жизнь.

2021-07-27 11:06 UTC, elukianov commented
> В виде объектов? Или айдишек?

Агрегаты друг на друга лучше ссылать через них, тк нам не нужен полный граф зависимостей в памяти

> А эти объекты могут и не понадобиться совсем. Мы сможем доставать их из хранилища целиком потом, когда потребуются.

Для того, чтобы доставать объекты частями, скажем для отображения пользователям, можно воспользоваться принципом CQRS

> Не разобралась - когда использовать DomainEntity, когда агрегат?
Если есть вложенные сущности, которые должны сохраняться только вместе с содержащим их объектом - то агрегат?
Например - айтемы у заказа.
А если вложенные могут сохраняться отдельно? Тогда DomainEntity? Или тоже агрегат?
Например - самолёт у рейса. Их ведь не нужно сохранять в одной транзакции.

Если совсем упростить, то агрегат - это данные, которые должны быть сохранены атомарно, то есть по ним проходит граница транзакции. У агрегата есть корень - это DE (например заказ). Внутри агрегата могут быть другие VO и DE, но они работают как единое целое.  Агрегат отвествтенен за сохранение инваринта, все операции проходят через него. Допустим мы решили вернуть один билет из заказа. OrderItem помечается как возвращенный (в нашем примере такого нет, но представим). Отвечать за возврат должен агрегат - Order.returnItem(). Именно поэтому работа с хранилищем идет через Агрегат, а не через DE

2021-07-27 11:07 UTC, elukianov requested changes
Написал немного комментариев

2021-07-27 14:12 UTC, polinkot commented
> Написал немного комментариев

Спасибо! Буду разбираться.

2021-07-31 17:52 UTC, polinkot commented
> Написал немного комментариев

Запушила исправления. Все кроме LessThanHourTillDeparture. Это наверно можно будет проверить только когда реализуем use case или персистенс? Нам же нужно получить время рейса. А у нас в билете только айдишка рейса.

2021-08-06 10:09 UTC, elukianov approved these changes

2021-08-06 10:13 UTC, merged